AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Yet Another Crypto Grid Bot (for AWS Lambda)

Globals:
  Function:
    MemorySize: 256
    Runtime: python3.8
    Timeout: 30
    CodeUri: function/.
    Layers:
      - !Ref libs
Resources:
  synctickers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: synctickers.lambda_handler
      Description: Call a crypto exchange, pull OHLCV data and put in dynamodb
      Timeout: 20
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
  backtest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: backtest.lambda_handler
      Description: Using historical OHLCV data in dynamodb, test crypto gbot parameters 
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
  liveinit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: liveinit.lambda_handler
      Description: Setup a new gbot running against a live account on an exchange
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
  liverun:
    Type: AWS::Serverless::Function
    Properties:
      Handler: liverun.lambda_handler
      Description: Run a gbot periodically to execute new trades based on its configuration
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
        - AmazonSSMReadOnlyAccess
      Tracing: Active
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: yacgb-lib
      Description: Dependencies for the yacgb app
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
