AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  yacgb

  Template for yacgb (Yet Another Crypto Grid Bot)

Resources:
  synctickers:
    Type: AWS::Serverless::Function
    Properties:
      Handler: synctickers.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Call a crypto exchange, pull OHLCV data and put in dynamodb
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
  backtest:
    Type: AWS::Serverless::Function
    Properties:
      Handler: backtest.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Using historical OHLCV data in dynamodb, test crypto gbot parameters 
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
  liveinit:
    Type: AWS::Serverless::Function
    Properties:
      Handler: liveinit.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Setup a new gbot running against a live account on an exchange
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
  liverun:
    Type: AWS::Serverless::Function
    Properties:
      Handler: liverun.lambda_handler
      Runtime: python3.8
      CodeUri: function/.
      Description: Run a gbot periodically to execute new trades based on its configuration
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AmazonDynamoDBFullAccess
      Tracing: Active
      Layers:
        - !Ref libs
  libs:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: yacgb-lib
      Description: Dependencies for the yacgb app
      ContentUri: package/.
      CompatibleRuntimes:
        - python3.8
